version: "3.9"

services:
  virtualwallet-db:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: virtualwallet
      TZ: America/Sao_Paulo
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - virtualwallet-network

networks:
  virtualwallet-network:
    driver: bridge