security:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY:my-secret-key}
      expire-length: 3600000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/virtualwallet
    username: postgres
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
